name: E2E Tests

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup Playwright
      run: npx playwright install --with-deps

    - name: Run End-to-End tests
      run: npm run test:e2e